### ISSUE TITLE
Documentation ! help

### ISSUE THREAD

**Issue by stlsw** [adebisi-fa/ngrok-dotnet-api#1]
I have built my own ngrok server, is it possible to integrate my own ngrok service with this ngrok wrapper, it seems that this assembly still needs the ngrok client, can you provide some documentationon this matter ? much appreciated.

**Comment by adebisi-fa** [comment]
Hello @StevenLiSiwei,

Glad to hear you have an ngrok server, though I'll like to know how it differs to ngrok.exe (functionality, launching, etc)? 

> It seems that this assembly still needs the ngrok client

If I get your point, yes, this library is usable ONLY when ngrok.exe is running.  It connects to ngrok.exe on http://localhost:4040 (or whatever port the service is running on)

SINCERE APOLOGY FOR THIS VERY LONG DELAY IN REPSONSE (Over a year, now, WHAO!) 

Sorry, please!

Hope this helps.
